name: CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest

      - name: Test cmd
        run: go test -v ./cmd

      - name: Test util
        run: go test -v ./util

      - name: Build
        run: go build -o spectra

      - name: Smoke test
        run: |
          chmod +x spectra
          ./spectra --help
